--- 
eureka: 
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka"
  instance: 
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"
    preferIpAddress: true
server: 
  port: 0
spring: 
  application: 
    name: content
